Repository Mudano/ui-react, pull requests merged in 2018-02, with the labels that each got.

#56 Unit test helpers
  package.json
  src/components/Avatar/Avatar.test.js
  src/components/Avatar/AvatarCard.test.js
  src/components/Avatar/AvatarTitle.js
  src/components/Avatar/AvatarTitle.test.js
  src/components/Button/Button.test.js
  src/components/Tooltip/Tooltip.test.js
  src/components/Tooltip/TooltipBox.test.js
  test/unit/commonTests/addsClassName.js
  test/unit/commonTests/addsComponentClassName.js
  test/unit/commonTests/index.js
  test/unit/commonTests/isConformant.js
  test/unit/commonTests/noClassNameFromUndefinedProp.js
  test/unit/commonTests/propKeyToClassName.js
  test/unit/commonTests/rendersTag.js
  test/unit/utils/classNameUtils.js
  test/unit/utils/index.js
  yarn.lock
Labels: Hide From Changelog, Ready For Review

#52 Tabs Component
  lib/IconMore.js
  lib/Tabs.js
  lib/index.js
  src/components/Button/Button.scss
  src/components/Button/Button.story.js
  src/components/Icon/IconArrow.js
  src/components/Icon/IconMore.js
  src/components/Icon/IconMore.story.js
  src/components/Icon/IconMore.test.js
  src/components/Tabs/Tabs.js
  src/components/Tabs/Tabs.story.js
  src/components/Tabs/Tabs.test-int.js
  src/components/Tabs/Tabs.test.js
  src/components/Tabs/TabsNav.js
  src/components/Tabs/TabsNav.scss
  src/components/Tabs/TabsNavItem.js
  src/components/Tabs/TabsNavItem.scss
  src/components/Tabs/TabsPane.js
  src/components/Tabs/TabsPane.scss
  src/components/Tabs/TabsPanes.js
  src/components/Tabs/TabsPanes.scss
  src/storybook-addons/utils.js
Labels: Ready For Review

#58 Release v1.2.0
  CHANGELOG.md
  package.json
Labels: Release Request

#64 Release v2.0.0
  CHANGELOG.md
  package.json
Labels: Release Request

#69 Release v2.0.1
  CHANGELOG.md
  package.json
Labels: Release Request

#66 Button resizes to contain confirmation text
  src/components/Button/Button.js
  src/components/Button/Button.scss
  src/components/Button/Button.story.js
  src/components/Button/Button.test.js
Labels: Ready For Review

#73 fix changelog to include time
  CHANGELOG.md
  release-src/changelog.js
Labels: Hide From Changelog

#74 change pr filter function
  release-src/changelog.js
Labels: Hide From Changelog

#75 Release v2.0.2
  CHANGELOG.md
  package.json
Labels: Release Request

#76 Clear button triggers input change
  src/components/Fields/TextField.js
  src/components/Fields/TextField.story.js
  src/components/Fields/TextField.test.js
Labels: Ready For Review

#77 Tweak PR template to match previous PRs and changelog
  .github/PULL_REQUEST_TEMPLATE
Labels: Hide From Changelog, Ready For Review

#78 Release v2.0.3
  CHANGELOG.md
  package.json
Labels: Release Request
