Repository Mudano/ui-react, pull requests merged in 2018-05, with the labels that each got.

#101 AvatarMenu Component
  lib/AvatarMenu.js
  lib/index.js
  src/components/Avatar/AvatarMenu.js
  src/components/Avatar/AvatarMenu.scss
  src/components/Avatar/AvatarMenu.story.js
  src/components/Avatar/AvatarMenu.test-int.js
  src/components/Avatar/AvatarMenu.test.js
  src/components/Avatar/AvatarMenu/AvatarMenuEnums.js
  src/components/Avatar/AvatarMenu/AvatarMenuItem.js
  src/components/Avatar/AvatarMenu/AvatarMenuItem.test.js
  src/components/Avatar/AvatarMenu/AvatarMenuNav.js
  src/components/Avatar/AvatarMenu/AvatarMenuNav.test.js
  src/components/Fields/TextArea.scss
  src/components/Fields/TextField.scss
  src/components/Icon/Icon.scss
  src/components/Tabs/Tabs.test.js
  yarn.lock
Labels: Ready For Review

#107 AvatarMenu bug fixes
  src/components/Avatar/AvatarMenu.js
  src/components/Avatar/AvatarMenu.scss
  src/components/Avatar/AvatarMenu.story.js
  src/components/Avatar/AvatarMenu/AvatarMenuItem.js
  src/components/Avatar/AvatarMenu/AvatarMenuNav.js
  src/components/Fields/TextArea.scss
  src/components/Fields/TextField.scss
Labels: Hide From Changelog, Ready For Review

#109 Remove double breadcrumbs in menu
  src/components/Breadcrumbs/Breadcrumbs.story.js
Labels: Hide From Changelog, Ready For Review

#110 Release v3.1.0
  CHANGELOG.md
  package.json
Labels: Release Request

#111 Set flatpickr version to 4.3.2 and fix DateField
  package.json
  yarn.lock
Labels: Approve For Merge

#113 Release v3.2.0
  CHANGELOG.md
  package.json
Labels: Release Request
